### ISSUE TITLE
Post Chat Message API throws error message: `Could not find a chat with the id xxx`

### ISSUE THREAD

**Issue by vunguyenhung** [ThreadsHQ/api-documentation#2]
I faced an error thrown by Threads Post Chat Message API
![image](https://user-images.githubusercontent.com/18277920/193956698-3604cba2-3b50-489b-8357-0cf89bf59c82.png)

Even though I have added the Chat ID correctly
![image](https://user-images.githubusercontent.com/18277920/193956784-474850cf-15b5-4872-a149-1d1b904c2602.png)

**Comment by svenkat45** [comment]
@vunguyenhung - appreciate the report 🙏🏽 This should now be fixed! Let us know if you're still hitting any issues.

**Comment by vunguyenhung** [comment]
Thanks @svenkat45, I verify that the API works correctly, will close the issue now.
